---
name: CI/CD
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Validate configuration
        run: |
          cd ${GITHUB_WORKSPACE}/configuration
          terraform init
          terraform validate
          terraform fmt -check -recursive

      - name: Validate deployment
        run: |
          cd ${GITHUB_WORKSPACE}/deployment
          terraform init
          terraform fmt -check -recursive

          cd ${GITHUB_WORKSPACE}/deployment/modules
          for dir in $(find . -type d -not \( -name ".?*" \) -maxdepth 1 -mindepth 1);
          do
            echo "Checking module ${dir}..."
            cd ${GITHUB_WORKSPACE}/deployment/modules/${dir}
            terraform init
            terraform validate
          done